---

- name: calculate stat of import file
  stat:
    path: "{{ role_path }}/templates/{{ hostvars[inventory_hostname].name }}.sh"
  register: stat_result

- name: check open-cluster-management-agent pods
  shell: |
    oc get pods -n open-cluster-management-agent
  register: result
  ignore_errors: true

- name: "run import {{ hostvars[inventory_hostname].name }} command"
  script: "{{ role_path }}/templates/{{ hostvars[inventory_hostname].name }}.sh"
  delegate_to: localhost
  register: output
  when:
  - stat_result.stat.exists
  - "'Running' not in result.stdout"

- name: output import command
  debug:
    msg: "{{ output.stdout_lines }}"
  when: 
  - stat_result.stat.exists
  - "'Running' not in result.stdout"